name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Show SSH Key (first few chars for debug, optional)
        run: |
                echo "${{ secrets.SSH_KEY }}" | head -c 100
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
            host: 13.201.4.19
            username: ubuntu
            key: ${{ secrets.SSH_KEY }}
            port: 22
            script:
                cd CI-CD-CM
                git pull
                npm install
                npm run build
                npm run start
                echo "Hello, world!"

